name: Index Repository
description: This will crawl the main branch file structure, using a .gitignore as a filter. It will then build up an index of the files and folders in the repository.

on:
  push:
    branches:
      - main

jobs:
  build_repository_index:
    runs-on: ubuntu-latest

    # env:
    #   IN_DIR: "./"
    #   OUT_DIR: "./"
    #   INDEX_NAME: "vault"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Run Obsidious Indexer (remote version)
        run: |
          npm exec remark-obsidious@latest --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }}

      - name: Upload the index and log files
        uses: actions/upload-artifact@v4
        with:
          name: obsidious-index
          path: |
            ${{ github.workspace }}/obsidious-index.json
            ${{ github.workspace }}/obsidious-index.log