name: Index Repository
description: This will crawl the main branch file structure, using a .gitignore as a filter. It will then build up an index of the files and folders in the repository.

on:
  push:
    branches:
      - main

jobs:
  build_repository_index:
    runs-on: ubuntu-latest

    env:
      # The indexer will begin crawling the repository from this directory
      IN_DIR: "./"
      # The indexer will create the repository index json file and log files in this directory
      OUT_DIR: "./"
      # Both the index and log files will be prefixed with this string
      # The index file will be named <INDEX_NAME>.json
      # The log files will be named <INDEX_NAME>.log
      INDEX_NAME: "vault"

    steps:
      - name: Confirm env vars
        run: |
          echo "IN_DIR: $IN_DIR"
          echo "OUT_DIR: $OUT_DIR"
          echo "INDEX_NAME: $INDEX_NAME"
          
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Run Obsidious Indexer (remote version)
        run: |
          npm exec remark-obsidious@latest --yes -- --in $IN_DIR --out $OUT_DIR --indexName $INDEX_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }}

      - name: Upload the index and log files
        uses: actions/upload-artifact@v4
        with:
          name: obsidious-index
          path: |
            ${{ github.workspace }}/$OUT_DIR/$INDEX_NAME.json
            ${{ github.workspace }}/$OUT_DIR/$INDEX_NAME.log